### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by xdaraboz** [jcsotpin/steam#4]
-Mostrar carroussel con fotos de juegos en inicio
-Tienda: mostrar tabla con juegos y demas para poder comprarlos
-Biblioteca: mostrar los juegos del cliente, si es suscriptor mostrar todos y agregar formulario con checkboxes/radiobuttons para mostrar los juegos filtrados
-Usuario: posiblemente añadir si es subscriptor  o no y cambiar así el estado del cliente en la """BBDD""".

**Comment by AlvMur** [comment]
-Compra de juegos del cliente
- Método _buscarSubscripcion gestionar las fechas para no poder suscribirte mientras tengas una subscripcion vigente.

**Comment by xdaraboz** [comment]
- arreglar comaparacion de subscripciones ( isAfter)
- agregar boton y formualrio en tabla tienda con datos del juego para comprar insertando el dni

**Comment by xdaraboz** [comment]
- agregar filtro en biblioteca
- agregar formulario en biblioteca para cambiar de cliente

**Comment by xdaraboz** [comment]
- Si acaso cambiar el filtrado de boton filtrar por un addEventListener al pulsar la opcion del combo

**Comment by xdaraboz** [comment]
1. Carrussel/imagenes en el index
2. Biblioteca : Form cliente para saber que cliente es y mostrar juegos + filtrado
3. Comprar Juego //DANI
4. Arreglar metodo _buscarSubscripcion
5. El si acaso cambiar el filtro
6. Inicio
